[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
comfy-table = "7.1.1"
csv = "1.3.0"
rand = "0.8.5"
serde = {version = "1.0.210", features = ["derive"]}
